### ISSUE TITLE
Mint 21 Python error

### ISSUE THREAD

**Issue by JDunstall** [imLinguin/nile#11]
Hey, getting this error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/jay/Downloads/nile/nile/cli.py", line 8, in <module>
    from nile.downloading import manager
  File "/home/jay/Downloads/nile/nile/downloading/manager.py", line 7, in <module>
    from nile.models import manifest, hash_pairs, patch_manifest
  File "/home/jay/Downloads/nile/nile/models/manifest.py", line 4, in <module>
    from Crypto.PublicKey import RSA
ModuleNotFoundError: No module named 'Crypto'
```
I definitely have all the depndicies installed, in particular python3-pycryptodome. Any ideas what to do?

Thanks.

**Comment by imLinguin** [comment]
If package manager way didn't work try `pip install pycryptodome`

**Comment by JDunstall** [comment]
That was it thanks!
