### ISSUE TITLE
qurl error trying to run

### ISSUE THREAD

**Issue by Code-Slave** [imLinguin/nile#19]
all i get is this every time. setup a venv and installed deps

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data3/nile/nile/cli.py", line 13, in <module>
    from nile.api import authorization, session, library
  File "/data3/nile/nile/api/authorization.py", line 3, in <module>
    from nile.gui import webview
  File "/data3/nile/nile/gui/webview.py", line 2, in <module>
    from PyQt5.Qt import QUrl
ImportError: cannot import name 'QUrl' from 'PyQt5.Qt' (/data3/nile/env/lib/python3.10/site-packages/PyQt5/Qt.abi3.so)

**Comment by imLinguin** [comment]
You probably also need QT libraries to be installed on your system

**Comment by imLinguin** [comment]
I'll remove the QT dependency in a moment. Will just open login link in a browser

**Comment by imLinguin** [comment]
Try latest commit now

**Comment by Code-Slave** [comment]
that did it. prefer cli anyway. thanks
