### ISSUE TITLE
JSON error when launching installed game

### ISSUE THREAD

**Issue by gteachey** [imLinguin/nile#26]
I'm able to install Amazon Games, but trying to launch it with nile keeps giving me a JSON error

```
(nile) suollecram@suoldesk:~/dev/nile$ ./bin/nile launch 2f8ca7a1-f0db-4179-bf06-9227f74fcafa
INFO [CLI]:	 Searching for 2f8ca7a1-f0db-4179-bf06-9227f74fcafa
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/suollecram/dev/nile/nile/cli.py", line 238, in <module>
    sys.exit(main())
  File "/home/suollecram/dev/nile/nile/cli.py", line 225, in main
    cli.handle_launch()
  File "/home/suollecram/dev/nile/nile/cli.py", line 184, in handle_launch
    launcher.start(found["path"])
  File "/home/suollecram/dev/nile/nile/utils/launch.py", line 90, in start
    instruction = LaunchInstruction.parse(
  File "/home/suollecram/dev/nile/nile/utils/launch.py", line 22, in parse
    json_data = json.loads(raw_data)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 9 column 3 (char 181)
(nile) suollecram@suoldesk:~/dev/nile$ 

```
How do I get games to launch with this app?

**Comment by cutiecactus** [comment]
It looks to be an issue with loading the game's data found in `fuel.json`. Unfortunately I don't have that game to try to recreate the error. Please could you go to the game's directory and show what the `fuel.json` file looks like? It appears to not be valid JSON from the error message.

**Comment by gteachey** [comment]
Yes that was the problem. The fuel.json had an extra comma in it

```
{
 "SchemaVersion":  "2",
 "PostInstall": [
   {
       "Command": "dependencies\\oalinst.exe",
       "Args": ["/quiet", "/norestart"],
       "ValidReturns": [ 0, 5100 ]
   }, <<-- BAD COMMA HERE
  ],
 "Main": {
   "Command": "Baldur.exe",
   "Args": []
 }
}
```

Once I deleted it the game was able to run. Much appreciated!

**Comment by gteachey** [comment]
Closing my issue now

**Comment by imLinguin** [comment]
This is some weird kind of JSON though. I'll try to fix the parsing
