### ISSUE TITLE
object is not subscriptable

### ISSUE THREAD

**Issue by matchuek** [imLinguin/nile#48]
```
matchi@ubuntu-l560:~/Downloads/nile-1.0.3$ bin/nile install -i amzn1.adg.product.625256c0-9e82-47e3-9bcb-7d1154a7d4a8 
INFO [CLI]:	 Found: Heaven Dust 2
ERROR [LIBRARY]:	 There was an error getting game manifest
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/matchi/Downloads/nile-1.0.3/nile/cli.py", line 347, in <module>
    sys.exit(main())
  File "/home/matchi/Downloads/nile-1.0.3/nile/cli.py", line 328, in main
    cli.handle_install()
  File "/home/matchi/Downloads/nile-1.0.3/nile/cli.py", line 161, in handle_install
    self.download_manager.info(self.arguments.json)
  File "/home/matchi/Downloads/nile-1.0.3/nile/downloading/manager.py", line 153, in info
    self.manifest = self.get_manifest()
  File "/home/matchi/Downloads/nile-1.0.3/nile/downloading/manager.py", line 31, in get_manifest
    self.version = game_manifest["versionId"]
TypeError: 'NoneType' object is not subscriptable

matchi@ubuntu-l560:~/Downloads/nile-1.0.3$ bin/nile --version
1.0.3 Jonathan Joestar

```

**Comment by imLinguin** [comment]
It seems you are using the old version, please try the latest code from main

**Comment by matchuek** [comment]
working like a charm! thanx
