### ISSUE TITLE
requests.exceptions.JSONDecodeError

### ISSUE THREAD

**Issue by matchuek** [imLinguin/nile#50]
Hi there,

getting this error in a fresh environment:
```
$ rm -r ~/.config/nile/

$ ./nile_linux_x86_64 --version
1.1.1 Will A. Zeppeli

$ ./nile_linux_x86_64 auth -l
[...]
INFO [AUTH_MANAGER]:	 Got authorization code
INFO [AUTH_MANAGER]:	 Registerring a device. ID: <cut>
INFO [AUTH_MANAGER]:	 Succesfully registered a device
INFO [AUTH_MANAGER]:	 Written data to the config
INFO [LIBRARY]:	 Synchronizing library
Traceback (most recent call last):
  File "requests/models.py", line 974, in json
  File "json/__init__.py", line 346, in loads
  File "json/decoder.py", line 337, in decode
  File "json/decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nile/cli.py", line 354, in <module>
  File "nile/cli.py", line 329, in main
  File "nile/cli.py", line 59, in handle_auth
  File "nile/api/authorization.py", line 217, in login
  File "nile/api/authorization.py", line 180, in handle_redirect
  File "nile/api/library.py", line 109, in sync
  File "requests/models.py", line 978, in json
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[5223] Failed to execute script 'cli' due to unhandled exception!
```

**Comment by imLinguin** [comment]
Try the latest commit. Amazon seems to have migrated entitlement service like they did with downloads too

**Comment by matchuek** [comment]
Thanks mate, working like a charm again!

**Comment by circlesmiler** [comment]
Are there any instruction on how to get this work on SteamDeck? Do I have to compile it for myself? The Ubuntu build does not seem to work.

**Comment by imLinguin** [comment]
it works on the deck, ensure the following
- did you mark the downloaded binary as executable? 
- is the binary in place where Heroic sandbox always has access to?

Heroic will soon receive an patch containing new version of nile

**Comment by circlesmiler** [comment]
@imLinguin Mark as executable did the trick! Nice! Not sure if this is obvious. Maybe you could add this to the documentation somewhere?
