### ISSUE TITLE
Importing games doesn't work

### ISSUE THREAD

**Issue by hawkeye116477** [imLinguin/nile#55]
Version: 1.1.2

I tried `nile.exe import amzn1.adg.product.3779e9cb-56b9-4f31-937c-16d18ddc8610 --path "C:/Amazon Games/Library/Kraken Academy"` and I got that long error:
```
INFO [CLI]:      Searching for amzn1.adg.product.3779e9cb-56b9-4f31-937c-16d18ddc8610
INFO [IMPORT]:          Verifying local files
Traceback (most recent call last):
  File "nile\cli.py", line 354, in <module>
  File "nile\cli.py", line 343, in main
  File "nile\cli.py", line 302, in handle_import
  File "nile\utils\importer.py", line 76, in import_game
  File "nile\utils\importer.py", line 44, in verify_integrity
  File "nile\utils\importer.py", line 25, in get_patchmanifest
KeyError: 'downloadUrls'
[PYI-27492:ERROR] Failed to execute script 'cli' due to unhandled exception
```

**Comment by imLinguin** [comment]
Thanks for reporting, and sorry for not much activity from my side. I have fixed the issue in latest commit.  

Also, thank you for developing amazing plugins for Playnite, that integrate nile and heroic-gogdl. This means a lot to me as the author of these tools
