### ISSUE TITLE
Doesn't launch on Arch

### ISSUE THREAD

**Issue by Galcian79** [imLinguin/nile#8]
Traceback (most recent call last):
File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
exec(code, run_globals)
File "/home/fulvio/nile/nile/cli.py", line 8, in <module>
from nile.downloading import manager
File "/home/fulvio/nile/nile/downloading/manager.py", line 7, in <module>
from nile.models import manifest, hash_pairs, patch_manifest
File "/home/fulvio/nile/nile/models/manifest.py", line 1, in <module>
from nile.proto import sds_proto2_pb2 as sds
File "/home/fulvio/nile/nile/proto/sds_proto2_pb2.py", line 5, in <module>
from google.protobuf.internal import enum_type_wrapper
ModuleNotFoundError: No module named 'google'

**Comment by imLinguin** [comment]
Install `sudo pacman -S python-protobuf`

**Comment by Galcian79** [comment]
Ok. I'm not sure if this tool has a gui yet,
Upon logging in it just drops me to the CLI with:

`INFO [AUTH_MANAGER]:     Spawning login window
[89603:24:0724/114413.487822:ERROR:batching_media_log.cc(38)] MediaEvent: {"error":"FFmpegDemuxer: no supported streams"}
[89603:1:0724/114413.492558:ERROR:batching_media_log.cc(35)] MediaEvent: {"pipeline_error":14}
[89603:24:0724/114444.488301:ERROR:batching_media_log.cc(38)] MediaEvent: {"error":"FFmpegDemuxer: no supported streams"}
[89603:1:0724/114444.489470:ERROR:batching_media_log.cc(35)] MediaEvent: {"pipeline_error":14}
INFO [AUTH_MANAGER]:     Got authorization code
INFO [AUTH_MANAGER]:     Registerring a device. ID: 3141433330453341304233353131454441333239324346444131363141413246234132554d56484f58375550345637
INFO [AUTH_MANAGER]:     Succesfully registered a device
INFO [AUTH_MANAGER]:     Written data to the config
INFO [LIBRARY]:  Synchronizing library
INFO [LIBRARY]:  Successfully synced the library`

**Comment by imLinguin** [comment]
there is no GUI yet, you can use `--help` to see available commands

**Comment by Galcian79** [comment]
> there is no GUI yet, you can use `--help` to see available commands

so i can just ignore those errors

**Comment by imLinguin** [comment]
yes these are coming from the webengine that pops up to login. At the bottom of the log you can see successful message. Everything else should work nicely
